# Reference:- TS 29.531 R16.0.0., Section- 6.1.6 Data Model
info:
  version: 1.4.0
  description: OAI-NSSF Legacy-aligned slicing configuration
configuration:
  nsiInfoList:
    - snssai:
        sst: 1
        sd: 'FFFFFF'
      nsiInformationList:
        nrfId: http://192.168.70.130:8080/nnrf-disc/v1/nf-instances
        nsiId: '1'
    - snssai:
        sst: 1
        sd: '000002'
      nsiInformationList:
        nrfId: http://192.168.70.130:8080/nnrf-disc/v1/nf-instances
        nsiId: '2'
  taInfoList:
    - tai:
        plmnId:
          mcc: '001'
          mnc: '01'
        tac: '0x0001'
      supportedSnssaiList:
        - sst: 1
          sd: 'FFFFFF'
        - sst: 1
          sd: '000002'
  amfInfoList:
    - targetAmfSet: oai5gcn.mcc001.mnc001.regionid80.setid1.3gppnetwork.org
      nrfAmfSet: http://192.168.70.130:8080/nnrf-disc/v1/nf-instances
      nrfAmfSetNfMgtUri: http://192.168.70.130:8080/nnrf-nfm/v1/nf-instances
      amfList:
        - nfId: legacy-amf-instance
          supportedNssaiAvailabilityData:
            tai:
              plmnId:
                mcc: '001'
                mnc: '01'
              tac: '0x0001'
            supportedSnssaiList:
              - sst: 1
                sd: 'FFFFFF'
              - sst: 1
                sd: '000002'
